import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "../components/Layout";

export const metadata = {
	title: "BOOGHCHEH",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Layout>{children}</Layout>
				
			</body>
		</html>
	);
}
