import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "../components/Layout";
import { ShoppingCartContextProvider } from "../context/ShoppingCartContext";

export const metadata = {
	title: "BOOGHCHEH",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ShoppingCartContextProvider>
					<Layout>{children}</Layout>
				</ShoppingCartContextProvider>
			</body>
		</html>
	);
}
